# Introdu√ß√£o - JavaScript ass√≠ncrono
A forma mais comum de lidar com c√≥digos ass√≠ncronos em Javascript s√£o as Promises. Mas, antes de falarmos sobre elas, voc√™ sabe o que √© um c√≥digo ass√≠ncrono!?

## Por que usar c√≥digos ass√≠ncronos

A principal vantagem de se trabalhar com um c√≥digo ass√≠ncrono √© poder executar outras fun√ß√µes sem travar a execu√ß√£o do programa principal enquanto o resultado da fun√ß√£o ass√≠ncrona n√£o √© finalizado.

Existem v√°rias situa√ß√µes onde voc√™ ir√° precisar trabalhar com c√≥digos ass√≠ncronos, como, por exemplo:

- Leitura e escrita de arquivos: como opera√ß√µes em disco tendem a ser demoradas, geralmente elas s√£o realizadas de forma ass√≠ncrona.

- Acesso a alguns recursos do navegador: recursos que dependem de hardware, como lidar com a c√¢mera, por exemplo.

- Fazer requisi√ß√µes externas: esse provavelmente √© o cen√°rio onde a assincronicidade √© mais utilizada. √â necess√°rio aguardar uma resposta do servidor ap√≥s fazer uma requisi√ß√£o sem travar a execu√ß√£o do resto do sistema.

## Promises

Promises s√£o ferramentas poderosas que o Javascript possui para lidar com c√≥digos ass√≠ncronos, por isso vamos nos aprofundar nesse assunto.

>> Promise √© um objeto usado para processamento ass√≠ncrono. Um Promise (de ‚Äúpromessa‚Äù) representa um valor que pode estar dispon√≠vel agora, no futuro ou nunca.

### Estados da promise
Uma promise pode ter tr√™s estados:

- pending (pendente): √© o estado inicial dela, ou seja, ela ainda est√° aguardando o t√©rmino da execu√ß√£o do c√≥digo ass√≠ncrono;

- fulfilled (realizada): quando a opera√ß√£o ass√≠ncrona foi realizada com sucesso. Tamb√©m √© comum dizer que quando a promise est√° nesse estado ela est√° resolvida;

- rejected (rejeitada): quando a opera√ß√£o ass√≠ncrona termina com algum erro.

## Construindo uma promise

Se quisermos criar nossas pr√≥prias promises podemos usar o construtor new Promise() para criar uma nova promise. Esse construtor recebe uma fun√ß√£o como par√¢metro e essa fun√ß√£o dever√° ter dois argumentos: a fun√ß√£o resolve e a fun√ß√£o reject.

``new Promise((resolve, reject) => {});``

Os par√¢metros resolve e reject ser√£o usados para definirmos qual o estado que promise ter√° quando for finalizada.

- Quando a promise for resolvida, usamos a fun√ß√£o resolve;
- Quando a promise for rejeitada, usamos a fun√ß√£o reject.

## Os m√©todos Then, Catch e Finally

Os m√©todos .then(), .catch(), e .finally() s√£o utilizados em promessas no JavaScript para lidar com o fluxo de execu√ß√£o ass√≠ncrona e tratar erros. Eles s√£o parte integrante do conceito de Promises (Promessas) e s√£o usados para controlar o resultado de uma opera√ß√£o ass√≠ncrona.


- .then( ): O m√©todo .then() √© usado para definir o tratamento de sucesso de uma promessa.
- .catch( ): O m√©todo .catch() √© usado para lidar com erros ocorridos durante a execu√ß√£o de uma promessa.
- .finally( ): O m√©todo .finally() √© usado para definir um bloco de c√≥digo que ser√° executado independentemente de a promessa ter sido resolvida ou rejeitada. 

````
resolvedPromise().then((resolve) => {
    console.log(`resolvedPromise: O n√∫mero gerado √© ${resolve}`)
}).catch((error) => {
    console.log(`Com a promise resolvida, n√£o ir√° passar pelo catch`);
}).finally(() => console.log('Fim da execu√ß√£o da segunda promise'));
````
## O m√©todo fetch( )

E o Javascript j√° nos fornece um m√©todo nativo para lidarmos com requisi√ß√µes externas: o m√©todo fetch(), que retorna uma promise, que pode ser resolvida ou rejeitada de acordo com o resultado da requisi√ß√£o.

O m√©todo fetch recebe dois par√¢metros:

``fetch(URL, config)``

- URL (obrigat√≥rio): √© o endere√ßo da API para qual faremos a requisi√ß√£o;
- Objeto de configura√ß√µes (opcional): caso a requisi√ß√£o precise de alguma configura√ß√£o adicional, √© poss√≠vel defini-la nesse objeto.

````
// Requisi√ß√£o GET sem nenhuma configura√ß√£o - recupera as informa√ß√µes de um produto.
fetch('https://dummyjson.com/products/27')
  .then((response) => response.json())
  .then((data) => console.log('GET sem headers', data));
````

>> De olho na dica üëÄ: Voc√™ reparou que usamos dois .then seguidos ap√≥s fazer o fetch? Esse processo √© chamado de encadeamento. Podemos usar esse recurso retornando um valor dentro de um .then. O valor retornado ser√° recebido pelo pr√≥ximo .then encadeado. No caso acima, estamos retornando o valor de response.json() para o pr√≥ximo .then, que recebe o valor atrav√©s da vari√°vel data.

### Tratando erros em requisi√ß√µes
Apesar de ser uma situa√ß√£o comum, fazer requisi√ß√µes nem sempre d√£o certo. √Ås vezes algum erro pode acontecer, como o servidor externo ficar indispon√≠vel, ou alguma configura√ß√£o ser passada de forma errada para o fetch.

````
fetch('https://dummyjson.com/products/321032109')
  .then((response) => response.json())
  .then((data) => console.log(data))
  .catch((error) => console.log('Erro ao fazer requisi√ß√£o', error.message))
````

## Trabalhando com v√°rias promises
Ao trabalhar com c√≥digos ass√≠ncronos, √© muito comum precisarmos lidar com mais de uma promise por vez. Seja por que voc√™ precisa esperar o resultado de duas ou mais promises, ou por que voc√™ precisa fazer v√°rias chamadas e pegar o resultado somente da que retornar mais r√°pido. O Javascript oferece quatro m√©todos que nos ajudam a trabalhar com v√°rias promises:

- Promise.all
- Promise.race
- Promise.any
- Promise.allSettled

### M√©todo Promise.all

- Par√¢metro recebido: array de promises

- Retorno: o retorno varia de acordo com a situa√ß√£o:

quando todas promises s√£o resolvidas: retorna uma promise resolvida com um array com o resultado de cada promise recebida.

````
Promise.all([
  generateResolvedPromise(1000),
  generateResolvedPromise(3000),
  generateResolvedPromise(2000),
])
  .then((result) => {
    console.log(result);
  })
  .catch((error) => console.log(error.message));
````
- quando uma promise √© rejeitada: retorna uma promise rejeitada com o objeto o erro retornado pela promise que foi rejeitada.

### M√©todo Promise.race

- Par√¢metro recebido: array de promises

- Retorno: o retorno varia de acordo com a situa√ß√£o:

quando a primeira promise finalizada for resolvida: retorna uma promise resolvida com o valor retornado pela primeira promise original.

quando a primeira promise finalizada for rejeitada: retorna uma promise rejeitada com o objeto o erro retornado pela promise original.

> Aten√ß√£o ‚ö†Ô∏è: mesmo que Promise.race s√≥ receba o valor da primeira promise a ser finalizada e ignore o valor das outras promises, todas as promises passadas como par√¢metro ser√£o executadas.

### M√©todo Promise.any
- Par√¢metro recebido: array de promises

- Retorno: o retorno varia de acordo com a situa√ß√£o:

quando alguma promise finalizada for resolvida: retorna uma promise resolvida com o valor retornado pela primeira promise original, ignorando qualquer outra promise que tenha sido finalizada primeiro como rejeitada.

quando todas as promise forem rejeitadas: retorna uma promise rejeitada com o objeto contendo todos os erros retornados pelas promises originais.

>Aten√ß√£o ‚ö†Ô∏è: mesmo que Promise.any s√≥ receba o valor da primeira promise a ser realizada e ignore o valor das outras promises, todas as promises passadas como par√¢metro ser√£o executadas.

### M√©todo Promise.allSettled
- Par√¢metro recebido: array de promises

- Retorno: retorna uma √∫nica promise que √© resolvida quando todas as promises passadas forem finalizadas. A promise √© retornada com um array de objetos que cont√©m o valor retornado por cada uma das promises originais.

## Async e Await

### O funcionamento do operador await
Quando colocamos o operador await no JavaScript, a execu√ß√£o do c√≥digo √© pausada at√© que a referida Promise seja resolvida. Isso significa que o c√≥digo n√£o ser√° executado al√©m daquela linha enquanto a Promise estiver pendente.

````
const a = funcaoQueRetornaPromise();
const b = await funcaoQueRetornaPromise();

console.log(a) // Aqui o console vai imprimir a Promise em si.
console.log(b) // Aqui o console vai imprimir o resultado da Promise
````

No c√≥digo acima, a vari√°vel a ser√° uma Promise (que pode inclusive ainda estar pendente). A execu√ß√£o do c√≥digo n√£o √© pausada nesse caso. Por essa raz√£o, o valor da vari√°vel √© uma Promise. Por outro lado, na vari√°vel b, o c√≥digo √© pausado at√© que a Promise seja resolvida (ou rejeitada) e o valor da vari√°vel ser√° o resultado dessa Promise, e n√£o a Promise em si.

‚ö†Ô∏è Um cuidado que devemos ter √© que, para usar o operador await dentro de uma fun√ß√£o, √© necess√°rio que ela seja uma fun√ß√£o ass√≠ncrona (com o operador async).

## Fun√ß√µes Ass√≠ncronas

Uma fun√ß√£o ass√≠ncrona √© uma fun√ß√£o que retorna uma Promise. N√≥s podemos tornar qualquer fun√ß√£o ass√≠ncrona simplesmente adicionando o operador async antes da sua declara√ß√£o. Por exemplo:

````
// Essa fun√ß√£o retorna o n√∫mero 1.
function foo() {
  return 1;
}

// Essa fun√ß√£o retorna uma Promise (que resolve no n√∫mero 1).
async function bar() {
  return 1;
}
````

## Lidando com Erros

Aprendemos que podemos tratar os erros lan√ßados dentro de uma Promise com o operador .catch(). Entretanto, quando usamos a sintaxe de async/await geralmente lidamos com erros usando blocos try/catch.

No nosso exemplo do cep:

````
const cep = '30130-010';
try {
  const response = await fetch(`https://viacep.com.br/ws/${cep}/json/`);
  const data = await response.json();
  console.log(data);
} catch(error) {
  console.log(error)
}
````

Na aplica√ß√£o acima, o c√≥digo tenta (try) fazer a requisi√ß√£o. Caso haja um erro, esse erro √© capturado (catch) e, no nosso caso, escolhemos tratar o erro imprimindo no nosso console. Voc√™ poder√° tratar o erro da maneira como desejar (por exemplo, com um alerta, enviando para a base de dados, logs, etc).

## Testes ass√≠ncronos

### A aplica√ß√£o que iremos testar
Antes de testar nossa aplica√ß√£o, vamos fazer algumas modifica√ß√µes e refatora√ß√µes para:

1. Extrair para um arquivo separado a l√≥gica ass√≠ncrona de busca de cep (separando, assim, as responsabilidades das fun√ß√µes);
2. Lan√ßar um erro quando nenhum valor for passado para o cep;
3. Lan√ßar um erro lan√ßado quando passamos um cep inv√°lido.

### Quando a requisi√ß√£o √© bem sucedida, ela dever√° retornar os dados esperados

No teste abaixo, √© importante adicionarmos o operador async no segundo argumento da fun√ß√£o test(). Isso faz com que seja poss√≠vel usarmos o operador await para esperarmos os dados da nossa fun√ß√£o getAddressFromCep(), que √© ass√≠ncrona.

````
test('deve retornar os dados quando passamos um cep v√°lido', async () => {
  const address = await getAddressFromCep('30130010');
  expect(address.cep).toBe('30130-010');
  expect(address.logradouro).toBe('Pra√ßa Sete de Setembro');
  expect(address.bairro).toBe('Centro');
  expect(address.uf).toBe('MG');
});
````
Em seguida vamos testar que nossa fun√ß√£o retorna os dados esperados independentemente de passarmos o cep com ou sem h√≠fen:

````
test('deve aceitar cep com h√≠fen ou sem h√≠fen', async () => {
  let address = await getAddressFromCep('30130010');
  expect(address.cep).toBe('30130-010');

  address = await getAddressFromCep('30130-010');
  expect(address.cep).toBe('30130-010');
});
````

### Quando a requisi√ß√£o √© rejeitada, ela dever√° retornar erro

Agora precisamos realizar os testes caso a requisi√ß√£o √† API n√£o seja bem sucedida.

### Ao passar um cep vazio

Al√©m de utilizarmos async/await como nos testes anteriores, nesse caso precisaremos tamb√©m de um matcher especial do Jest. Como estamos testando a rejei√ß√£o de uma Promise, precisamos usar o helper rejects combinado com o matcher toThrow, que testar√° o erro que foi lan√ßado.

Neste caso tamb√©m estamos testando a mensagem de erro lan√ßada. Por esse motivo precisamos criar um erro com a mensagem esperada, utilizando a sintaxe new Error('Mensagem de erro'), junto do matcher toThrow.

````
test('Deve lan√ßar erro "Voc√™ precisa passar um CEP" quando passar cep vazio', async () => {
  const emptyCep = '';

  await expect(getAddressFromCep(emptyCep)).rejects.toThrow(
    new Error('Voc√™ precisa passar um CEP')
  );
});
````

### Ao passar um cep inv√°lido

Da mesma forma, tamb√©m vamos testar ceps inv√°lidos. Nesse caso estamos apenas testando que haver√° um erro, e n√£o a mensagem do erro. Por essa raz√£o, podemos usar o toThrow sem nenhum argumento.

````
test('Deve lan√ßar erro quando passar cep inv√°lido', async () => {
  const invalidCep = 'XXXXX-XXX';
  const invalidCepLessDigits = '00000-00';
  const invalidCepMoreDigits = '00000-0000';

  await expect(getAddressFromCep(invalidCep)).rejects.toThrow();
  await expect(getAddressFromCep(invalidCepLessDigits)).rejects.toThrow();
  await expect(getAddressFromCep(invalidCepMoreDigits)).rejects.toThrow();
});
````

√â importante perceber que, em alguns testes, n√£o estamos testando nossa aplica√ß√£o, mas sim o retorno da API. Para testarmos a nossa aplica√ß√£o de fato, precisamos utilizar o mock da fun√ß√£o fetch. Mas tenha tranquilidade, uma vez que iremos aprender esse t√≥pico mais √† frente no curso.

O mais comum √© testarmos nossa aplica√ß√£o com mocks. Por√©m, testar o retorno da API, como fizemos nos testes acima, pode ser v√°lido quando queremos garantir que estamos recebendo os dados corretos. Entretanto, √© importante saber que, ao testarmos a API:

Os testes ficam mais demorados, uma vez que dependem de resposta externa;
Os testes podem quebrar quando h√° indisponibilidade desta API;
Algumas APIs possuem limites de requisi√ß√£o que podem ser feitas - fique atento a eles.
O Jest possui tamb√©m outras formas de testes ass√≠ncronos. Voc√™ pode verificar na documenta√ß√£o da biblioteca.